Week1
aglabx/edusummer2021 pull request #10
Opened 2021-06-13 15:43 UTC by tniapp

Лёша, тут только розалинд и кодворс, решения пока положила в виде Юпитер ноутбука в соответствующие папки

2021-06-13 19:23 UTC, ad3002 commented
Мне не сделать ревью на файле юпитера, он выглядит вот так:

![image](https://user-images.githubusercontent.com/142793/121819470-e76ff680-cc95-11eb-9b68-208b9f406617.png)

Нужно сделать, как написано в инструкции

2021-06-13 20:14 UTC, ad3002 requested changes

2021-06-13 20:14 UTC, ad3002 commented on students/tniapp/codewars/Codewars.ipynb
> +{
Нужно оформить для код ревью и обратить внимание на название коммитов

2021-06-16 07:23 UTC, ad3002 requested changes
В целом все работает, но нужно поправить название переменных и часть задачек переписать в более коротком виде

2021-06-16 07:23 UTC, ad3002 commented on students/tniapp/rosalind/week1_solutions.md
> +        a = int(line.split()[0])
это нужно одной строкой a, b, c = map(int, line.strip().split())

2021-06-16 07:23 UTC, ad3002 commented on students/tniapp/rosalind/week1_solutions.md
> +        if len(line) == 1:
Неа, данные нужно читать по строчно из файла без цикла, тут всегда две строки и только их и нужно прочитать.

2021-06-16 07:23 UTC, ad3002 commented on students/tniapp/rosalind/week1_solutions.md
> +string = string[0]
это не нужно, длина строки по условию всегда меньше или ровна 200

2021-06-16 07:23 UTC, ad3002 commented on students/tniapp/rosalind/week1_solutions.md
> +        line = line.strip().split()
нужно одной строкой как выше

2021-06-16 07:23 UTC, ad3002 commented on students/tniapp/rosalind/week1_solutions.md
> +    for number in range(a, b, 2):
не типичное решение, попробуй найти стандартное, когда цикл и внутри проверка на четность и если нужное число со суммировать, код будет значительно короче

2021-06-16 07:23 UTC, ad3002 commented on students/tniapp/rosalind/week1_solutions.md
> +cnt = 1
cnt - это что? не экономь буквы, называй переменные читаемо =)

2021-06-16 07:23 UTC, ad3002 commented on students/tniapp/rosalind/week1_solutions.md
> +        line = line.strip().split()
line - это строка же, у тебя слева уже не строка,
нужно называть переменные по их содержанию, например,
слева может быть word_list

2021-06-16 07:23 UTC, ad3002 commented on students/tniapp/rosalind/week1_solutions.md
> +            if word not in word2count.keys():
посмотри про dict.defaultvalue или про Counter

2021-06-16 11:53 UTC, tniapp commented
Внесла правки в розалинд и оформила codewars

2021-06-22 14:03 UTC, tniapp commented
Добавила конспект Кунина по первой неделе

2021-06-25 16:42 UTC, closed without merging