Week1 preparations =)
aglabx/edusummer2021 pull request #3
Opened 2021-06-08 18:34 UTC by Abusagit

Делал в консоли и тупанул и сделал все изменения в одном коммите, не бейте :(

2021-06-10 08:42 UTC, ad3002 requested changes

2021-06-10 08:42 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return - number
не очень  питон хотя работает, так на JS было бы норм, лучше -1 *

2021-06-10 08:42 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return 'Even' if number % 2 == 0 else 'Odd'
Вот это хорошо!

2021-06-10 08:42 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return 'Even' if number % 2 == 0 else 'Odd'
Можно еще короче, без === 0 сравнения

2021-06-10 08:42 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return num_vowels
Вообще тут ожидается решение другое, во всех таких задачках, через return sum(...) одной строкой

2021-06-10 08:42 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    vowels = ('aeiouAEIOU')
Лучше взять в привычку что символ одинарные кавычки, а строки двойные

2021-06-10 08:42 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +        string_ = string_.replace(vowel, '')
Есть без цикла идиоматическое решение, например оно ипользуется для реверс комплемента ДНК, так как очень быстрое

2021-06-10 08:42 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return ppg_1 + ppg_2
Тут все же логичней сразу вернуть сумму, не вынимая переменные

2021-06-10 08:42 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return ppg_1 + ppg_2
И опять же одна строка будет

2021-06-10 08:42 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +        return f'{names[0]}, {names[1]} and {names[2]} like this'
Двойные кавычки. Это для удобства работы с C/C++ и др языками потом

2021-06-10 08:42 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +def array_diff(a, b):
Нет. Одной строкой. Тогда будешь попадать решением в best practice. Ты похоже просто не знаешь эти идиомы, или не используешь.

2021-06-10 08:42 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    vowels = ('aeiouAEIOU')
Везде по заданию.

2021-06-10 09:43 UTC, Abusagit commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return 'Even' if number % 2 == 0 else 'Odd'
Ааа, потому что 0 уже будет ложью?

2021-06-10 09:44 UTC, Abusagit commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return num_vowels
Можно завести словарь и потом sum(<кортеж значений словаря в ячейках гласных>)

Будет однопроходка

2021-06-10 09:47 UTC, Abusagit commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return ppg_1 + ppg_2
Можно, но что если была бы обманка, и нужно было искать ключи с числовыми значениями? Я хотел сделать проверку на это, оставил переменные

2021-06-10 10:10 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return num_vowels
нет, тут не нужен словарь, еще проще

2021-06-10 10:15 UTC, ad3002 requested changes

2021-06-10 10:15 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return - 1 * number
Лишний пробел -1 - это не знак минусу, это число -1

2021-06-10 10:15 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return 'Odd' if number % 2 else 'Even'
Да!

2021-06-10 10:15 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    vowels_unicode = (ord(vowel) for vowel in 'aeiou')
Проще. Просто пройдись по строке, тут одна строка должна быть, всего одна

2021-06-10 10:15 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return [item for item in a if item not in b]
ДА! и вот выше такое же

2021-06-10 10:30 UTC, ad3002 requested changes

2021-06-10 10:30 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return sum(1 for letter in input_str if letter in 'aeiou') # Если прям одна строка то минус память
Ну ты можешь сделать с reduce =) Но это оверкил. Если тебе не нравится по памяти, то делает просто
```
for letter in input_str:
    if letter in 'aeiou':
         c += 1
```

2021-06-10 10:30 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return ''.join(letter for letter in string_ if letter not in 'aeiouAEIOU')
Отлично! Это еще в соревнованиях на скорость позволяет быстро писать.

2021-06-10 10:31 UTC, ad3002 commented
Каты - приняты. Дальше делай.

2021-06-10 10:53 UTC, ad3002 requested changes

2021-06-10 10:53 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return reduce(lambda x, y: x + 1 if y in "aeiou" else x + 0, letters)
x+0 не нужен, он ничего не делает

2021-06-10 10:53 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    letters = [0] + [i for i in input_str]
ну это слишком, все гораздо проще! functools.reduce(function, iterable[, initializer])

2021-06-10 10:54 UTC, Abusagit commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return reduce(lambda x, y: x + 1 if y in "aeiou" else x + 0, letters)
Согласен,x + 0 остался с прошлых попыток

2021-06-10 10:54 UTC, Abusagit commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    letters = [0] + [i for i in input_str]
ААА

2021-06-10 10:54 UTC, Abusagit commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    letters = [0] + [i for i in input_str]
Ждите-с

2021-06-10 10:56 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return reduce(lambda x, y: x + 1 if y in "aeiou" else x + 0, letters)
и перепиши это без if else, это избыточно, достаточно суммы

2021-06-10 11:17 UTC, ad3002 requested changes

2021-06-10 11:17 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return reduce(lambda x, y: x + 1 if y in "aeiou" else x + 0, input_str, 0) # Без закрытого тернарного выражения нельзя
вот это x + 1 if y in "aeiou" else x + 0 перепиши короче, как сумму числа и бул

2021-06-10 11:18 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return reduce(lambda x, y: x + 1 if y in "aeiou" else x + 0, input_str, 0) # Без закрытого тернарного выражения нельзя
тут нет тернарного выражения, это не развилка

2021-06-10 11:32 UTC, Abusagit commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return reduce(lambda x, y: x + 1 if y in "aeiou" else x + 0, input_str, 0) # Без закрытого тернарного выражения нельзя
Сработало

2021-06-10 11:38 UTC, ad3002 requested changes

2021-06-10 11:38 UTC, ad3002 commented on students/fvelikonivtsev/codewars/week1_solutions.md
> +    return reduce(lambda x, y: x + (y in "aeiou"), input_str, 0)
Да!

2021-06-16 07:56 UTC, ad3002 commented on students/fvelikonivtsev/koonin/chapter1.md
> +* Добржанский
Нам бы тул который граф делает терминов

2021-06-16 09:10 UTC, Abusagit commented on students/fvelikonivtsev/koonin/chapter1.md
> +* Добржанский
С взаимосвязями?

2021-06-25 16:38 UTC, merged