Week1
aglabx/edusummer2021 pull request #9
Opened 2021-06-12 18:09 UTC by KoptelovaEkaterina

2021-06-13 20:09 UTC, ad3002 commented
Мне не сделать код ревью на ноутбук, посмотри в описание задания как надо оформить https://github.com/aglabx/edusummer2021

2021-06-13 20:15 UTC, ad3002 requested changes

2021-06-13 20:15 UTC, ad3002 commented on students/KoptelovaEkaterina/codewars_1.ipynb
> +{
Нужно оформить для код ревью и обратить внимание на название коммитов

2021-06-16 07:31 UTC, ad3002 requested changes
Решения рабочие! осталось их причесать и чуть ускорить

2021-06-16 07:31 UTC, ad3002 commented on students/KoptelovaEkaterina/codewars/week1_solutions.md
> +    return number* -1
пробел и число все же до переменной красивей писать

2021-06-16 07:31 UTC, ad3002 commented on students/KoptelovaEkaterina/codewars/week1_solutions.md
> +    if number%2 == 0:
пробелы тут и ниже должно быть 1 + 1

2021-06-16 07:31 UTC, ad3002 commented on students/KoptelovaEkaterina/codewars/week1_solutions.md
> +def get_count(input_str):
Это очееееень долго считает, тут время O(n*n*logn), а должно быть O(n)
Попробуй переписать используя только один цикл

2021-06-16 07:31 UTC, ad3002 commented on students/KoptelovaEkaterina/codewars/week1_solutions.md
> +    string_ = string_.replace('a','')
Во-первых, ты забыла заглавные буквы. И опять это долго считает, попробуй тоже переписать одной строкой, используя лист куда ты будешь складывать правильные буквы, а потом соберешь строку через ''.join(list)

2021-06-16 07:31 UTC, ad3002 commented on students/KoptelovaEkaterina/codewars/week1_solutions.md
> +    playerOne = { 'team': '76ers', 'ppg': 11.2 }
не нужно внутри создавать эти словари, ты же передаешь их как переменные

2021-06-16 07:31 UTC, ad3002 commented on students/KoptelovaEkaterina/codewars/week1_solutions.md
> +def get_middle(s):
Так. Очень сложно получилось, попробуй просто считать средний символ, тут можно сильно короче. И у тебя почему-то три варианта событий, а условия же только два, четная или нечетная длина строки

2021-06-16 19:44 UTC, KoptelovaEkaterina commented
Ок, спасибо

ср, 16 июн. 2021 г., 10:32 Aleksey Komissarov ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Решения рабочие! осталось их причесать и чуть ускорить
> ------------------------------
>
> In students/KoptelovaEkaterina/codewars/week1_solutions.md
> <https://github.com/aglabx/edusummer2021/pull/9#discussion_r652419950>:
>
> > @@ -0,0 +1,91 @@
> +## [1. Opposite number](https://www.codewars.com/kata/56dec885c54a926dcd001095/train/python)
> +```python
> +def opposite(number):
> +  # your solution here
> +    return number* -1
>
> пробел и число все же до переменной красивей писать
> ------------------------------
>
> In students/KoptelovaEkaterina/codewars/week1_solutions.md
> <https://github.com/aglabx/edusummer2021/pull/9#discussion_r652420228>:
>
> > @@ -0,0 +1,91 @@
> +## [1. Opposite number](https://www.codewars.com/kata/56dec885c54a926dcd001095/train/python)
> +```python
> +def opposite(number):
> +  # your solution here
> +    return number* -1
> +
> +```
> +## [2. Even or Odd]( https://www.codewars.com/kata/53da3dbb4a5168369a0000fe/train/python)
> +
> +```python
> +def even_or_odd(number):
> +    if number%2 == 0:
>
> пробелы тут и ниже должно быть 1 + 1
> ------------------------------
>
> In students/KoptelovaEkaterina/codewars/week1_solutions.md
> <https://github.com/aglabx/edusummer2021/pull/9#discussion_r652421174>:
>
> > +
> +```
> +## [2. Even or Odd]( https://www.codewars.com/kata/53da3dbb4a5168369a0000fe/train/python)
> +
> +```python
> +def even_or_odd(number):
> +    if number%2 == 0:
> +        return "Even"
> +    if number%2 != 0:
> +        return "Odd"
> +```
> +
> +## [3 Vowel Count](https://www.codewars.com/kata/54ff3102c1bad923760001f3/train/python)
> +
> +```python
> +def get_count(input_str):
>
> Это очееееень долго считает, тут время O(n*n*logn), а должно быть O(n)
> Попробуй переписать используя только один цикл
> ------------------------------
>
> In students/KoptelovaEkaterina/codewars/week1_solutions.md
> <https://github.com/aglabx/edusummer2021/pull/9#discussion_r652421994>:
>
> > +        start = input_str.find("o", start+1)
> +        if start == -1:
> +            break
> +        count += 1
> +    while True:
> +        start = input_str.find("u", start+1)
> +        if start == -1:
> +            break
> +        count += 1
> +    return count
> +```
> +## [4 Disemvowel Trolls](https://www.codewars.com/kata/52fba66badcd10859f00097e/train/python)
> +
> +```python
> +def disemvowel(string_):
> +    string_ = string_.replace('a','')
>
> Во-первых, ты забыла заглавные буквы. И опять это долго считает, попробуй
> тоже переписать одной строкой, используя лист куда ты будешь складывать
> правильные буквы, а потом соберешь строку через ''.join(list)
> ------------------------------
>
> In students/KoptelovaEkaterina/codewars/week1_solutions.md
> <https://github.com/aglabx/edusummer2021/pull/9#discussion_r652422701>:
>
> > +        part = len(s)//2
> +        part1 = part - 1
> +        a = s[part1:-part1]
> +    else:
> +        part = len(s)//2 + 1
> +        part1 = part - 1
> +        a = s[part1:part]
> +    return a
> +```
> +
> +## [6 All Star Code Challenge #1](https://www.codewars.com/kata/5863f97fb3a675d9a700003f/train/python)
> +
> +```python
> +def sum_ppg(playerOne, playerTwo):
> +    # Your code here
> +    playerOne = { 'team': '76ers', 'ppg': 11.2 }
>
> не нужно внутри создавать эти словари, ты же передаешь их как переменные
> ------------------------------
>
> In students/KoptelovaEkaterina/codewars/week1_solutions.md
> <https://github.com/aglabx/edusummer2021/pull/9#discussion_r652424434>:
>
> > +
> +```python
> +def disemvowel(string_):
> +    string_ = string_.replace('a','')
> +    string_ = string_.replace('e','')
> +    string_ = string_.replace('i','')
> +    string_ = string_.replace('o','')
> +    string_ = string_.replace('u','')
> +    string_ = string_.replace('O','')
> +    return string_
> +```
> +
> +## [5  Get the Middle Character](https://www.codewars.com/kata/56747fd5cb988479af000028/train/python)
> +
> +```python
> +def get_middle(s):
>
> Так. Очень сложно получилось, попробуй просто считать средний символ, тут
> можно сильно короче. И у тебя почему-то три варианта событий, а условия же
> только два, четная или нечетная длина строки
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/aglabx/edusummer2021/pull/9#pullrequestreview-684812580>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASIBT5DJHKUIAU3SFYZWUDLTTBHPRANCNFSM46S6OJ7Q>
> .
>

2021-06-25 16:41 UTC, closed without merging